title: Lilium
url: https://github.com/szuliani/lilium-jekyll-theme/
author:
  name: Stefano Zuliani
  email: your-email@domain.com
  bio: Hi, my name is Stefano.

tagline: A simple blog theme for Jekyll
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

lilium:
  # date format. The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  date_format: "%b %d, %Y"
  home_post_to_display: 6
  footer_text: 'Made with ðŸ’š by <a href="https://zulianis.eu">Stefano Zuliani</a>. Available under <a href="https://opensource.org/licenses/MIT">MIT License</a>.'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


social_links:
  - title: Jekyll @ GitHub
    url: "https://github.com/jekyll/"
  - title: Jekyll @ X
    url: "https://x.com/jekyllrb"


defaults:
  -
    scope:
      path: "_posts"
    values:
      type: "post"
      layout: "post"
      img: ""

sass:
  sass_dir: _sass